const reasons = [
  'The beauty of your souls shines so bright',
  'You make me want to seek and love God more',
  'You drive me to become the best I can be',
  'Your smile is like light to everyone who sees it',
  'You are so compassionate',
  'You are genuine and true',
  'You are completely honest',
  'Your simple perspectives are always filled with wisdom',
  'Your joy is contagious',
  'You do not fear expression of yourself or of others',
  'Even when you are angry, you keep yourself in control',
  'You see the best in people',
  'You are strong',
  'You are courageous',
  'You are not judgemental',
  'You are trustworthy',
  'I love to see you laugh',
  'Your happiness makes me happy',
  'I love the sound of your voice',
  'I love to listen to you',
  'I love the vibe around you',
  'I love your soul in all its ever growing beauty',
  'I love your mind in its intriguing intellect and infinite potential',
  'I love your heart in its unapologetic show of affection',
  'I love your body for it is indeed the temple of God',
  'I love you in your joy',
  'I love you in your sadness',
  'I love you in your anger',
  'I love you in your disappoinment',
  'I love you in your success',
  'I love you in your failure',
  'I love you in your pride',
  'I love you in your humility',
  'I love your gracefulness',
  'I love your faithfulness',
  'I love your discipline',
  'I love your commitment (when you really commit)',
  'I love your elegance',
  'I love your light',
  'I love your shine',
  'I love the potential within you and I want to see it manifest',
  'I love everything God wants you to become',
  'I love the way you pray',
  'I love the way you thoroughly study the word of God',
  'I love the way you handle your relationships',
  'I love your intentionality',
  'I love your patience',
  'I love your eyes and cannot wait to look into them again',
  'I love your lips and the words that flow from them',
  'I love your hair, not too obedient not too stubborn',
  '"Have you seen the state of your body??!!!"',
  'I LOVE YOU Erianyo Lucy Omoregie',
  'Happy Valentine' + "'" + 's Day baby girl',
  'It is Ash Wednesday, it is time for us to fast and pray',
  'THE END',
];

export default reasons;
